# services/report_service.py
"""Build downloadable security-audit reports (Markdown and PDF).

fpdf2 is chosen over weasyprint/reportlab because it is pure Python with no system
libraries, so it installs cleanly on a free-tier host. Its core fonts are latin-1
only, so all text is sanitized before it reaches the PDF.
"""
import re
from datetime import datetime

SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]

# Strip emoji and anything else outside latin-1; fpdf2's core fonts reject them.
_EMOJI = re.compile(
    "[\U0001F000-\U0001FAFF\U00002190-\U000021FF\U00002300-\U000027BF\U0000FE00-\U0000FE0F]+",
    flags=re.UNICODE,
)


def sanitize(text) -> str:
    """Make text safe for fpdf2's latin-1 core fonts."""
    s = str(text or "")
    s = _EMOJI.sub("", s)
    return s.encode("latin-1", "replace").decode("latin-1")


def _today() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def _by_severity(findings):
    return {
        sev: [f for f in findings if f["severity"] == sev] for sev in SEVERITY_ORDER
    }


# ── Markdown ─────────────────────────────────────────────────────────
def build_markdown_report(audit: dict) -> str:
    summary = audit["summary"]
    counts = summary["counts"]
    findings = audit["findings"]
    lines = [
        f"# Security Audit Report",
        "",
        f"**Repository:** {audit['repo_name']}  ",
        f"**Generated:** {_today()}  ",
        f"**Files scanned:** {audit['files_scanned']}",
        "",
        "## Executive summary",
        "",
        f"**Grade {summary['grade']}** — security score **{summary['score']}/100**, "
        f"with **{summary['total']}** finding(s) across {audit['files_scanned']} source file(s).",
        "",
        "| Severity | Count |",
        "|---|---:|",
    ]
    for sev in SEVERITY_ORDER:
        lines.append(f"| {sev.capitalize()} | {counts.get(sev, 0)} |")

    if not audit.get("llm_used"):
        lines += ["", "> Static heuristics only — AI deep analysis was not run "
                      "(no API key configured)."]

    lines += ["", "## Findings", ""]
    if not findings:
        lines.append("No security issues were detected.")
    else:
        grouped = _by_severity(findings)
        for sev in SEVERITY_ORDER:
            items = grouped[sev]
            if not items:
                continue
            lines += [f"### {sev.capitalize()} ({len(items)})", ""]
            for f in items:
                lines += [
                    f"#### {f['title']}",
                    "",
                    f"- **File:** `{f['file']}`" + (f" (line {f['line']})" if f["line"] else ""),
                    f"- **Category:** {f['category']}  ",
                    f"- **CWE:** {f['cwe']}  ",
                    f"- **Confidence:** {f['confidence']} · **Detected by:** {f['source']}",
                    "",
                ]
                if f.get("description"):
                    lines += [f["description"], ""]
                if f.get("evidence"):
                    lines += ["```", f["evidence"], "```", ""]
                if f.get("remediation"):
                    lines += [f"**Remediation:** {f['remediation']}", ""]

    remediations = [f["remediation"] for f in findings if f.get("remediation")]
    if remediations:
        lines += ["## Remediation summary", ""]
        for r in dict.fromkeys(remediations):
            lines.append(f"- {r}")
        lines.append("")

    skipped = audit.get("files_skipped") or []
    if skipped:
        lines += ["## Coverage notes", "",
                  f"{len(skipped)} item(s) were not fully analyzed:", ""]
        for s in skipped:
            lines.append(f"- `{s['file']}` — {s['reason']}")
        lines.append("")

    lines += ["---", "", "_Generated by DevPulse Architect. "
              "Static heuristics and AI analysis can both produce false positives; "
              "review each finding before acting._"]
    return "\n".join(lines)


# ── PDF ──────────────────────────────────────────────────────────────
def _mc(pdf, height, text):
    """multi_cell that always starts at the left margin.

    fpdf2's multi_cell defaults to new_x=RIGHT, which leaves the cursor at the
    right edge; a following full-width multi_cell(w=0) then computes zero width
    and raises "Not enough horizontal space to render a single character".
    """
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, height, sanitize(text), new_x="LMARGIN", new_y="NEXT")


def build_pdf_report(audit: dict) -> bytes:
    from fpdf import FPDF

    summary = audit["summary"]
    counts = summary["counts"]
    findings = audit["findings"]

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, sanitize("Security Audit Report"), new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(0, 6, sanitize(f"Repository: {audit['repo_name']}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, sanitize(f"Generated: {_today()}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, sanitize(f"Files scanned: {audit['files_scanned']}"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Summary
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 9, sanitize("Executive summary"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    _mc(pdf, 6, f"Grade {summary['grade']} - security score {summary['score']}/100, "
                f"with {summary['total']} finding(s).")
    if not audit.get("llm_used"):
        pdf.set_font("Helvetica", "I", 9)
        _mc(pdf, 5, "Static heuristics only - AI deep analysis was not run "
                    "(no API key configured).")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 10)
    for sev in SEVERITY_ORDER:
        pdf.cell(35, 7, sanitize(sev.capitalize()), border=1)
        pdf.cell(20, 7, str(counts.get(sev, 0)), border=1, align="R",
                 new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Findings
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 9, sanitize("Findings"), new_x="LMARGIN", new_y="NEXT")

    if not findings:
        pdf.set_font("Helvetica", "", 11)
        _mc(pdf, 6, "No security issues were detected.")
    else:
        colors = {
            "critical": (220, 38, 38), "high": (234, 88, 12),
            "medium": (217, 119, 6), "low": (37, 99, 235), "info": (71, 85, 105),
        }
        for f in findings:
            pdf.ln(2)
            r, g, b = colors.get(f["severity"], (0, 0, 0))
            pdf.set_text_color(r, g, b)
            pdf.set_font("Helvetica", "B", 11)
            _mc(pdf, 6, f"[{f['severity'].upper()}] {f['title']}")

            pdf.set_text_color(90, 90, 90)
            pdf.set_font("Helvetica", "", 9)
            loc = f"{f['file']}" + (f":{f['line']}" if f["line"] else "")
            _mc(pdf, 5, f"{loc}  |  {f['category']}  |  {f['cwe']}")

            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", "", 10)
            if f.get("description"):
                _mc(pdf, 5, f["description"])
            if f.get("evidence"):
                pdf.set_font("Courier", "", 8)
                _mc(pdf, 4, f["evidence"])
            if f.get("remediation"):
                pdf.set_font("Helvetica", "I", 9)
                _mc(pdf, 5, f"Fix: {f['remediation']}")

    skipped = audit.get("files_skipped") or []
    if skipped:
        pdf.ln(4)
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, sanitize("Coverage notes"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for s in skipped:
            _mc(pdf, 5, f"- {s['file']}: {s['reason']}")

    out = pdf.output()
    return bytes(out)
